drop table if exists state_machine cascade;
drop table if exists ticket_state;
drop table if exists ticket_reviewer;
drop table if exists ticket_developer;
drop table if exists ticket;


create table state_machine
(
    machine_id     varchar(255) not null,
    state          varchar(255) not null,
    event          varchar(255) null,
    extended_state jsonb        null,
    updated_at     timestamp default current_timestamp,
    version        bigint    default 1,
    PRIMARY KEY (machine_id)
);

create table ticket
(
    id          int generated always as identity primary key,
    title       varchar(255) not null,
    state       varchar(255) not null,
    created_by  varchar(255) not null,
    description text         not null,
    created_at  timestamp,
    updated_at  timestamp
);

create table ticket_state
(
    machine_id varchar(255) not null,
    ticket_id  int          not null,
    constraint ticket_state_machine_id_fk foreign key (machine_id) references state_machine (machine_id),
    constraint ticket_state_ticket_foreign foreign key (ticket_id) references ticket (id)
);

create table ticket_reviewer
(
    id         int generated by default as identity primary key,
    vote       varchar(255)                        not null,
    comments   text                                null,
    ticket_id  int                                 not null,
    reviewer   varchar(100)                        not null,
    created_at timestamp default current_timestamp not null,
    updated_at timestamp default current_timestamp not null,
    constraint ticket_reviewer_ticket_id_fk foreign key (ticket_id) references ticket (id) on delete cascade
);


create table ticket_developer
(
    id          int                                 not null primary key,
    developer   varchar(100)                        not null,
    token_id    int                                 null,
    credentials text                                null,
    created_at  timestamp default current_timestamp not null,
    updated_at  timestamp default current_timestamp not null,
    constraint ticket_developer_id_fk
        foreign key (id) references ticket (id)
            on delete cascade
);
