package com.innogrid.statemachine;

public enum Events {
     // 메인 이벤트
    CREATE_TICKET,
    USER_CANCEL,
    REQUEST_APPROVED,
    REQUEST_ALL_APPROVED,
    REQUEST_REJECTED,
    DEVELOPMENT_COMPLETE,
    TEST_PASSED,
    TEST_FAILED,
    REVIEW_MERGED,
    MERGE_FAILED,
    BUILD_SUCCESS,
    BUILD_FAILED,
    BUILD_REJECTED,
    DEPLOY_SUCCESS,
    DEPLOY_FAILED,
    DEPLOY_REJECTED,
    CANCEL_REQUEST,
    CANCEL_APPROVED,
    CANCEL_REJECTED,
}
